#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
server:
  port: 9001
spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: ihrm-company #指定服务名
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  jpa:
    hibernate:
      ddl-auto: update
    database: MySQL
    show-sql: true
    open-in-view: true
