server:
  port: 9002
spring:
  application:
    name: ihrm-system #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: MySQL
    show-sql: true
    open-in-view: true
jwt:
  config:
    key: saas-ihrm
    ttl: 360000
